# Generated by Django 3.0.9 on 2020-08-22 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_auto_20200822_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todos',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('MODERATE', 'MODERATE')], max_length=20),
        ),
    ]
